/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "app/inc/cfg.h"

#if CFG_SAMPLE == CFG_SAMPLE_01_LED_TOGGLE

#include "hal/nucleo/f446re/inc/led.h"
#include "utils/inc/utils.h"

int main(void)
{
  const hal::nucleo::f446re::led led{};
  for (;;)
  {
    led.toggle();
    utils::delay();
  }
  return 0;
}
#endif
