/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "nucleof446re.h"
#include "cfg.h"

#if CFG_SAMPLE == CFG_SAMPLE_01_LED_TOGGLE

int main(void)
{
  nucleo::F446re h_nucleo{};
  h_nucleo.init_led();
  for (;;)
  {
    h_nucleo.wait_till_button_pressed();
    h_nucleo.toggle_led();
  }
  return 0;
}
#endif
