/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "drivers/peripherals/inc/gpio.h"
#include "utils.h"

int main(void)
{
  gpio_handle_t led;
  led.p_reg = GPIOA;
  led.cfg.number = GPIO_PIN_5;
  led.cfg.mode = GPIO_MODE_OUT;
  led.cfg.speed = GPIO_SPEED_FAST;
  led.cfg.out_type = GPIO_OUT_TYPE_PUSH_PULL;
  led.cfg.pull_mode = GPIO_PULL_MODE_NONE;

  gpio_enable_peripheral_clock(led.p_reg, true);
  gpio_init(&led);

  while (1)
  {
    gpio_toggle_pin(&led);
    Utils::delay();
  }

  return 0;
}
