#ifndef __CFG_H__
#define __CFG_H__

#define CFG_SAMPLE_01_LED_TOGGLE (0)
#define CFG_SAMPLE_02_LED_BUTTON (1)
#define CFG_SAMPLE_05_BUTTTON_INTERRUPT (2)
#define CFG_SAMPLE_06_SPI_SEND (3)
#define CFG_SAMPLE_07_SPI_TX_ONLY_ARDUINO (4)
#define CFG_SAMPLE_08_SPI_ARDUINO (5)
#define CFG_SAMPLE_09_SPI_ARDUINO_IT (6)
#define CFG_SAMPLE_010_I2C_MASTER_TX (7)
#define CFG_SAMPLE_11_I2C_MASTER_RX (8)
#define CFG_SAMPLE_12_I2C_MASTER_RX_IT (9)
#define CFG_SAMPLE_13_I2C_SLAVE_TX (10)
#define CFG_SAMPLE_14_I2C_SLAVE_TX_LEN (11)
#define CFG_SAMPLE_15_USART_TX (12)

#define CFG_SAMPLE (CFG_SAMPLE_05_BUTTTON_INTERRUPT)

#endif // __CFG_H__